final String SIGN_IN = 'signin';
final String SIGN_UP = 'signup';
final String SPLASH_SCREEN = 'splashscreen';
final String DROP_DOWN_FIELD_1 = "پایه ریاضی (دهم تا دوازدهم)"; //br
final String DROP_DOWN_FIELD_2 = "پایه انسانی (دهم تا دوازدهم)"; //ba
final String DROP_DOWN_FIELD_3 = "پایه تجربی (دهم تا دوازدهم)"; //bt
final String DROP_DOWN_FIELD_4 = "کنکور ریاضی"; //kr
final String DROP_DOWN_FIELD_5 = "کنکور تجربی"; //kt
final String DROP_DOWN_FIELD_6 = "کنکور انسانی";
final String DROP_DOWN_FIELD_7 = "کل آزمون ها";
final String DROP_DOWN_TITLE = " انتخاب نوع آزمون";
final String TEXT_FORM_FIELD_TITLE = "عنوان آزمون";
final String TEXT_FORM_FIELD_DESCRIPTION = "خلاصه متن آزمون";
final String BOTTON_NAV_ITEM_HOME = "خانه";
final String BOTTON_NAV_ITEM_USERS = "مدیران";
final String SPLASHSCREEN_TITLE = "بانک سوالات و آزمون ها";
final String SEND_QUIZE_BUTTON = "ارسال آزمون";
final String SIGNIN_WELLCOME_TEXT = "خوش آمدید";
final String SIGNIN_TEXT = "حساب کاربری خود را وارد کنید";
final String FORM_USERNAME = "نام کاربری";
final String FORM_OLD_PASSWORD = "پسورد قبلی";
final String FORM_NEW_PASSWORD = "پسورد جدید";
final String FORM_PASSWORD = "رمز عبور";
final String FORM_NAME = "نام";
final String FORM_LNAME = "نام خانوادگی";
final String FORM_EMAIL = "ایمیل";
final String FORM_RESET_PASSWORD = "بازیابی رمز عبور";
final String FORM_FORGET_PASSWORD_TEXT = "رمز عبور خود را فراموش کرده اید ؟";
final String FORM_NOT_ENY_ACCOUNT = "ایمیل";
final String FORM_SIGNIN_BUTTON_ENTER = "ورود";
final String FORM_CHANGE_PASSWORD_BUTTON = "تغییر رمز";
final String LOGIN_FAILED_TEXT = "کاربری با این نام کاربری ثبت نام نکرده است";
final String ACCOUNT_NOT_ACTIVATE_TEXT =
    "اکانت شما فعال نشده است برای فعال سازی ایمیل خود را بررسی کنید";
final String SERVER_NOT_RESPONSE_TEXT = "در حال حاضر سرور پاسخ گو نیست";
final String FORM_SIGNUP_TEXT = "ثبت نام";
final String FORM_NOT_HAVE_ACCOUNT_TEXT = "آیا هنوز هیچ حسابی ندارید ؟";
final String SINGUP_USER_EXIST = "کاربر با این مشخصات قبلا ثبت نام کرده است";
final String SINGUP_PASSWORD_COMMON = "لطفا رمز عبور مناسب تری انتخاب کنید";
final String SIGNUP_SUCCSESS_MESSEGE = "ثبت نام شما با موفقیت انجام شد";
final String SIGNUP_SUCCSESS_DESCRIPTION =
    "برای فعال سازی حساب خود,ایمیل خود را بررسی کرده و حساب خود را فعال کنید";
final String SIGNUP_SUCCSESS_BUTTON_TEXT = "تایید";
final String TEXT_FORM_FIELD_CHOSE = "انتخاب فایل";
